---
- name: Download JetBrains
  get_url:
    url: "{{ jetbrains_mono_url }}-{{ jetbrains_mono_version }}.zip"
    dest: /tmp/
    mode: '0755'

- name: Create a directory /usr/share/fonts if it does not exist
  become: true
  file:
    path: /usr/share/fonts
    state: directory
    mode: '0755'

- name: Unarchive font to /usr/share/fonts
  become: true
  unarchive:
    src: /tmp/JetBrainsMono-{{ jetbrains_mono_version }}.zip
    dest: /usr/share/fonts
    creates: /usr/share/fonts/JetBrainsMono-{{ jetbrains_mono_version }}
    remote_src: "yes"
