---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: create test users
      become: yes
      user:
        name: '{{ item }}'
        home: '/home/{{ item }}'
        createhome: yes
      loop:
        - test_usr1
        - test_usr2
        - test_usr3

  roles:
    - role: iancleary.zsh_antibody
      users:
        - username: test_usr1
        - username: test_usr2
        - username: test_usr3
