---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: install unzip for archive task
      apt: name=unzip state=present
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: iancleary.jetbrains_mono
